{% set name = "validators" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/validators-{{ version }}.tar.gz
  sha256: 4a70757730619a2c0788aa3c60ba1680372173237c445571586cdef02e37223b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8

test:
  imports:
    - validators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kvesteri/validators
  summary: Python Data Validation for Humans™
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    Python data validation for Humans.

    Python has all kinds of data validation tools, but every one of them seems to require defining a schema or form. I wanted to create a simple validation library where validating a simple value does not require defining a form or a schema.
  doc_url: https://validators.readthedocs.io/
  dev_url: https://github.com/kvesteri/validators

extra:
  recipe-maintainers:
    - brl0
    - xylar
